webtalk_init -webtalk_dir /home/centos/guide/aws-fpga/hdk/cl/developer_designs/cl_hello_world/verif/sim/vivado/test_hello_world/xsim.dir/tb/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May  1 09:13:08 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2_AR71275_op (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b0f818e5-4d98-48ec-af3f-104f9c7a4603" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "166c4b4d-d15b-4152-8b88-ef0cf25bfbc0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.5.1804 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2300.171 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "21650 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "49.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "397000_KB" -context "xsim\\usage"
webtalk_transmit -clientid 349817267 -regid "" -xml /home/centos/guide/aws-fpga/hdk/cl/developer_designs/cl_hello_world/verif/sim/vivado/test_hello_world/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.xml -html /home/centos/guide/aws-fpga/hdk/cl/developer_designs/cl_hello_world/verif/sim/vivado/test_hello_world/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.html -wdm /home/centos/guide/aws-fpga/hdk/cl/developer_designs/cl_hello_world/verif/sim/vivado/test_hello_world/xsim.dir/tb/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
